/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsManageRouteImport } from './routes/tests-manage'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StudentsManageRouteImport } from './routes/students-manage'
import { Route as SocialPortfolioRouteImport } from './routes/social-portfolio'
import { Route as MyTestsRouteImport } from './routes/my-tests'
import { Route as MyResultsRouteImport } from './routes/my-results'
import { Route as MyReportRouteImport } from './routes/my-report'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as MyClubsRouteImport } from './routes/my-clubs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CouncilRouteImport } from './routes/council'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as ClubsIndexRouteImport } from './routes/clubs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TestIdRouteImport } from './routes/test.$id'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as ClubsIdRouteImport } from './routes/clubs.$id'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminSchoolsRouteImport } from './routes/admin.schools'
import { Route as AdminRatingRouteImport } from './routes/admin.rating'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminCounselorsRouteImport } from './routes/admin.counselors'
import { Route as AdminCenterClubsRouteImport } from './routes/admin.center-clubs'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'

const TestsManageRoute = TestsManageRouteImport.update({
  id: '/tests-manage',
  path: '/tests-manage',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsManageRoute = StudentsManageRouteImport.update({
  id: '/students-manage',
  path: '/students-manage',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPortfolioRoute = SocialPortfolioRouteImport.update({
  id: '/social-portfolio',
  path: '/social-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTestsRoute = MyTestsRouteImport.update({
  id: '/my-tests',
  path: '/my-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const MyResultsRoute = MyResultsRouteImport.update({
  id: '/my-results',
  path: '/my-results',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportRoute = MyReportRouteImport.update({
  id: '/my-report',
  path: '/my-report',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClubsRoute = MyClubsRouteImport.update({
  id: '/my-clubs',
  path: '/my-clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilRoute = CouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIdRoute = TestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIdRoute = ClubsIdRouteImport.update({
  id: '/clubs/$id',
  path: '/clubs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchoolsRoute = AdminSchoolsRouteImport.update({
  id: '/admin/schools',
  path: '/admin/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRatingRoute = AdminRatingRouteImport.update({
  id: '/admin/rating',
  path: '/admin/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCounselorsRoute = AdminCounselorsRouteImport.update({
  id: '/admin/counselors',
  path: '/admin/counselors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCenterClubsRoute = AdminCenterClubsRouteImport.update({
  id: '/admin/center-clubs',
  path: '/admin/center-clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/council': typeof CouncilRoute
  '/dashboard': typeof DashboardRoute
  '/my-clubs': typeof MyClubsRoute
  '/my-profile': typeof MyProfileRoute
  '/my-report': typeof MyReportRoute
  '/my-results': typeof MyResultsRoute
  '/my-tests': typeof MyTestsRoute
  '/social-portfolio': typeof SocialPortfolioRoute
  '/students-manage': typeof StudentsManageRoute
  '/tasks': typeof TasksRoute
  '/tests-manage': typeof TestsManageRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/center-clubs': typeof AdminCenterClubsRoute
  '/admin/counselors': typeof AdminCounselorsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/rating': typeof AdminRatingRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/test/$id': typeof TestIdRoute
  '/admin/': typeof AdminIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/council': typeof CouncilRoute
  '/dashboard': typeof DashboardRoute
  '/my-clubs': typeof MyClubsRoute
  '/my-profile': typeof MyProfileRoute
  '/my-report': typeof MyReportRoute
  '/my-results': typeof MyResultsRoute
  '/my-tests': typeof MyTestsRoute
  '/social-portfolio': typeof SocialPortfolioRoute
  '/students-manage': typeof StudentsManageRoute
  '/tasks': typeof TasksRoute
  '/tests-manage': typeof TestsManageRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/center-clubs': typeof AdminCenterClubsRoute
  '/admin/counselors': typeof AdminCounselorsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/rating': typeof AdminRatingRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/test/$id': typeof TestIdRoute
  '/admin': typeof AdminIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/news': typeof NewsIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/council': typeof CouncilRoute
  '/dashboard': typeof DashboardRoute
  '/my-clubs': typeof MyClubsRoute
  '/my-profile': typeof MyProfileRoute
  '/my-report': typeof MyReportRoute
  '/my-results': typeof MyResultsRoute
  '/my-tests': typeof MyTestsRoute
  '/social-portfolio': typeof SocialPortfolioRoute
  '/students-manage': typeof StudentsManageRoute
  '/tasks': typeof TasksRoute
  '/tests-manage': typeof TestsManageRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/center-clubs': typeof AdminCenterClubsRoute
  '/admin/counselors': typeof AdminCounselorsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/rating': typeof AdminRatingRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/news/$id': typeof NewsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/test/$id': typeof TestIdRoute
  '/admin/': typeof AdminIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/council'
    | '/dashboard'
    | '/my-clubs'
    | '/my-profile'
    | '/my-report'
    | '/my-results'
    | '/my-tests'
    | '/social-portfolio'
    | '/students-manage'
    | '/tasks'
    | '/tests-manage'
    | '/admin/activity'
    | '/admin/applications'
    | '/admin/center-clubs'
    | '/admin/counselors'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/rating'
    | '/admin/schools'
    | '/admin/tasks'
    | '/clubs/$id'
    | '/news/$id'
    | '/students/$id'
    | '/test/$id'
    | '/admin/'
    | '/clubs/'
    | '/news/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/council'
    | '/dashboard'
    | '/my-clubs'
    | '/my-profile'
    | '/my-report'
    | '/my-results'
    | '/my-tests'
    | '/social-portfolio'
    | '/students-manage'
    | '/tasks'
    | '/tests-manage'
    | '/admin/activity'
    | '/admin/applications'
    | '/admin/center-clubs'
    | '/admin/counselors'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/rating'
    | '/admin/schools'
    | '/admin/tasks'
    | '/clubs/$id'
    | '/news/$id'
    | '/students/$id'
    | '/test/$id'
    | '/admin'
    | '/clubs'
    | '/news'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/council'
    | '/dashboard'
    | '/my-clubs'
    | '/my-profile'
    | '/my-report'
    | '/my-results'
    | '/my-tests'
    | '/social-portfolio'
    | '/students-manage'
    | '/tasks'
    | '/tests-manage'
    | '/admin/activity'
    | '/admin/applications'
    | '/admin/center-clubs'
    | '/admin/counselors'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/rating'
    | '/admin/schools'
    | '/admin/tasks'
    | '/clubs/$id'
    | '/news/$id'
    | '/students/$id'
    | '/test/$id'
    | '/admin/'
    | '/clubs/'
    | '/news/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CouncilRoute: typeof CouncilRoute
  DashboardRoute: typeof DashboardRoute
  MyClubsRoute: typeof MyClubsRoute
  MyProfileRoute: typeof MyProfileRoute
  MyReportRoute: typeof MyReportRoute
  MyResultsRoute: typeof MyResultsRoute
  MyTestsRoute: typeof MyTestsRoute
  SocialPortfolioRoute: typeof SocialPortfolioRoute
  StudentsManageRoute: typeof StudentsManageRoute
  TasksRoute: typeof TasksRoute
  TestsManageRoute: typeof TestsManageRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminCenterClubsRoute: typeof AdminCenterClubsRoute
  AdminCounselorsRoute: typeof AdminCounselorsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminRatingRoute: typeof AdminRatingRoute
  AdminSchoolsRoute: typeof AdminSchoolsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  ClubsIdRoute: typeof ClubsIdRoute
  NewsIdRoute: typeof NewsIdRoute
  StudentsIdRoute: typeof StudentsIdRoute
  TestIdRoute: typeof TestIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests-manage': {
      id: '/tests-manage'
      path: '/tests-manage'
      fullPath: '/tests-manage'
      preLoaderRoute: typeof TestsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students-manage': {
      id: '/students-manage'
      path: '/students-manage'
      fullPath: '/students-manage'
      preLoaderRoute: typeof StudentsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-portfolio': {
      id: '/social-portfolio'
      path: '/social-portfolio'
      fullPath: '/social-portfolio'
      preLoaderRoute: typeof SocialPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tests': {
      id: '/my-tests'
      path: '/my-tests'
      fullPath: '/my-tests'
      preLoaderRoute: typeof MyTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-results': {
      id: '/my-results'
      path: '/my-results'
      fullPath: '/my-results'
      preLoaderRoute: typeof MyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-report': {
      id: '/my-report'
      path: '/my-report'
      fullPath: '/my-report'
      preLoaderRoute: typeof MyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-clubs': {
      id: '/my-clubs'
      path: '/my-clubs'
      fullPath: '/my-clubs'
      preLoaderRoute: typeof MyClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council': {
      id: '/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof CouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$id': {
      id: '/test/$id'
      path: '/test/$id'
      fullPath: '/test/$id'
      preLoaderRoute: typeof TestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$id': {
      id: '/clubs/$id'
      path: '/clubs/$id'
      fullPath: '/clubs/$id'
      preLoaderRoute: typeof ClubsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schools': {
      id: '/admin/schools'
      path: '/admin/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rating': {
      id: '/admin/rating'
      path: '/admin/rating'
      fullPath: '/admin/rating'
      preLoaderRoute: typeof AdminRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/counselors': {
      id: '/admin/counselors'
      path: '/admin/counselors'
      fullPath: '/admin/counselors'
      preLoaderRoute: typeof AdminCounselorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/center-clubs': {
      id: '/admin/center-clubs'
      path: '/admin/center-clubs'
      fullPath: '/admin/center-clubs'
      preLoaderRoute: typeof AdminCenterClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CouncilRoute: CouncilRoute,
  DashboardRoute: DashboardRoute,
  MyClubsRoute: MyClubsRoute,
  MyProfileRoute: MyProfileRoute,
  MyReportRoute: MyReportRoute,
  MyResultsRoute: MyResultsRoute,
  MyTestsRoute: MyTestsRoute,
  SocialPortfolioRoute: SocialPortfolioRoute,
  StudentsManageRoute: StudentsManageRoute,
  TasksRoute: TasksRoute,
  TestsManageRoute: TestsManageRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminCenterClubsRoute: AdminCenterClubsRoute,
  AdminCounselorsRoute: AdminCounselorsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminRatingRoute: AdminRatingRoute,
  AdminSchoolsRoute: AdminSchoolsRoute,
  AdminTasksRoute: AdminTasksRoute,
  ClubsIdRoute: ClubsIdRoute,
  NewsIdRoute: NewsIdRoute,
  StudentsIdRoute: StudentsIdRoute,
  TestIdRoute: TestIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
