-- ============================================================================
-- BILIMNOMA "Kasblar" — CHUQUR KONTENT (2026-06-23)
--
--   Mavjud 35 kasb yozuviga `details` jsonb ichida qo'shimcha maydonlar qo'shadi
--   (pros / cons / day_in_life / quiz / resources / related) va cover rasm
--   (image_url) o'rnatadi. `details || '{...}'` — eski maydonlar (what/skills/...)
--   saqlanadi, faqat yangilari qo'shiladi/yangilanadi.
--
--   Cover rasmlar — AI-generatsiya (pollinations.ai); admin paneldan istalgan
--   vaqtda haqiqiy fotoga almashtirish mumkin. Matnlar dollar-quote ($j$/$q$)
--   ichida — apostroflar erkin; JSON qiymatlarida ikkilik tirnoq ishlatilmaydi.
--   IDEMPOTENT: WHERE title bo'yicha, qayta ishga tushsa bir xil natija.
-- ============================================================================

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/AI%20engineer%20working%20with%20neural%20networks%20on%20multiple%20monitors%20in%20a%20modern%20tech%20office%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Yuqori maosh va katta talab","Dunyoni o'zgartiradigan loyihalar","Masofadan ishlash imkoniyati"],"cons":["Doimiy yangi narsa o'rganish kerak","Murakkab matematika talab qiladi","Ko'p vaqt ekran oldida"],"day_in_life":["Ertalab jamoaviy uchrashuvda vazifalarni ko'rib chiqadi","Kunduzi ma'lumotlarni tayyorlab modelni o'rgatadi","Kechqurun natijani tekshirib yaxshilaydi"],"quiz":["Men matematika va mantiqni yoqtiraman","Men yangi texnologiyalarni o'rganishdan charchamayman","Men muammoni qismlarga bo'lib yechaman","Men sabr bilan tajriba o'tkaza olaman"],"resources":[{"label":"Kaggle (amaliyot)","url":"https://www.kaggle.com"},{"label":"Coursera kurslari","url":"https://www.coursera.org"}],"related":["Ma'lumotlar tahlilchisi (Data Scientist)","Dasturchi (dasturiy ta'minot muhandisi)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Sun'iy intellekt muhandisi$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/data%20scientist%20analyzing%20charts%20and%20graphs%20on%20computer%20screens%20modern%20office%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Har sohada talab katta","Qaror qabul qilishga ta'sir qiladi","Yaxshi daromad"],"cons":["Ko'p ma'lumotni tozalash zerikarli bo'lishi mumkin","Statistikani chuqur bilish kerak","Natija doim aniq bo'lavermaydi"],"day_in_life":["Ma'lumotlarni yig'ib tozalaydi","Diagramma va hisobotlar tayyorlaydi","Topilmalarni jamoaga tushuntiradi"],"quiz":["Men raqamlar va jadvallar bilan ishlashni yoqtiraman","Men qonuniyat izlashdan zavq olaman","Men diqqatli va sabrliman","Men xulosani sodda tushuntira olaman"],"resources":[{"label":"Kaggle","url":"https://www.kaggle.com"},{"label":"Stepik kurslari","url":"https://stepik.org"}],"related":["Sun'iy intellekt muhandisi","Dasturchi (dasturiy ta'minot muhandisi)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Ma'lumotlar tahlilchisi (Data Scientist)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/cybersecurity%20expert%20monitoring%20network%20security%20on%20dark%20screens%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Juda yuqori talab","Muhim va mas'uliyatli ish","Yaxshi maosh"],"cons":["Tahdidlar tinmay yangilanadi","Yuqori mas'uliyat va stress","Tayyor turish kerak bo'lishi mumkin"],"day_in_life":["Tizimlarni zaifliklarga tekshiradi","Hujum urinishlarini kuzatadi","Himoya choralarini yangilaydi"],"quiz":["Men detallarga juda e'tiborliman","Men jumboq va boshqotirmalarni yoqtiraman","Men mas'uliyatdan qo'rqmayman","Men tizim qanday ishlashini bilishni istayman"],"resources":[{"label":"TryHackMe","url":"https://tryhackme.com"},{"label":"Coursera","url":"https://www.coursera.org"}],"related":["Dasturchi (dasturiy ta'minot muhandisi)","Sun'iy intellekt muhandisi"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Kiberxavfsizlik mutaxassisi$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/robotics%20engineer%20building%20and%20testing%20a%20robot%20arm%20in%20a%20laboratory%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Mexanika va dasturni birga yaratish qiziq","O'sib borayotgan soha","Real qurilmalar yaratasiz"],"cons":["Bilim keng bo'lishi kerak (fizika va dastur)","Qurilmalar qimmat","Sinov ko'p vaqt oladi"],"day_in_life":["Robot qismlarini loyihalaydi","Dasturini yozib yuklaydi","Harakatlarini sinab sozlaydi"],"quiz":["Men narsalarni yig'ib-buzishni yoqtiraman","Men fizika va matematikani tushunaman","Men qo'lim bilan ishlashni yoqtiraman","Men muammoni bosqichma-bosqich yechaman"],"resources":[{"label":"Arduino","url":"https://www.arduino.cc"},{"label":"Coursera","url":"https://www.coursera.org"}],"related":["Dasturchi (dasturiy ta'minot muhandisi)","Dron operatori"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Robototexnika muhandisi$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/software%20developer%20writing%20code%20on%20laptop%20with%20dual%20monitors%20modern%20office%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Katta talab va yaxshi maosh","Masofadan va erkin ishlash","Ijodiy muammolar yechish"],"cons":["Uzoq vaqt o'tirib ishlash","Doimiy o'rganish","Ba'zan muddatlar qisqa"],"day_in_life":["Vazifani tushunib reja tuzadi","Kod yozib sinaydi","Xatolarni tuzatib topshiradi"],"quiz":["Men mantiqiy fikrlayman","Men muammoni qadam-baqadam yechaman","Men yangi narsa o'rganishni yoqtiraman","Men diqqatim bilan uzoq ishlay olaman"],"resources":[{"label":"freeCodeCamp","url":"https://www.freecodecamp.org"},{"label":"Stepik","url":"https://stepik.org"}],"related":["Sun'iy intellekt muhandisi","UX/UI dizayner"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Dasturchi (dasturiy ta'minot muhandisi)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/ux%20ui%20designer%20designing%20mobile%20app%20interface%20on%20computer%20creative%20studio%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Ijod va texnika uyg'unligi","Har sohada kerak","Foydalanuvchiga to'g'ridan-to'g'ri yordam"],"cons":["Did har xil — tanqid ko'p","Doimiy trend kuzatish","Mijoz talablari o'zgaruvchan"],"day_in_life":["Foydalanuvchi ehtiyojini o'rganadi","Ekran maketlarini chizadi","Sinab, dizaynni yaxshilaydi"],"quiz":["Men chiroyli va qulay narsalarni sevaman","Men odamlarni tushunishga harakat qilaman","Men chizish va dizaynni yoqtiraman","Men tanqidni xotirjam qabul qila olaman"],"resources":[{"label":"Figma","url":"https://www.figma.com"},{"label":"Behance","url":"https://www.behance.net"}],"related":["Grafik dizayner","Dasturchi (dasturiy ta'minot muhandisi)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$UX/UI dizayner$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/drone%20operator%20flying%20a%20professional%20drone%20over%20green%20fields%20at%20sunset%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Yangi va o'sayotgan soha","Ko'p sohalarda qo'llanadi","Sayohat va ochiq havoda ish"],"cons":["Ob-havoga bog'liq","Qonun va ruxsatlar talab qilinadi","Texnika qimmat"],"day_in_life":["Parvoz rejasini tayyorlaydi","Dronni uchirib suratga oladi","Ma'lumotni qayta ishlaydi"],"quiz":["Men texnikani boshqarishni yoqtiraman","Men diqqatli va ehtiyotkorman","Men ochiq havoda ishlashni sevaman","Men yangi narsani sinashdan qo'rqmayman"],"resources":[{"label":"DJI","url":"https://www.dji.com"},{"label":"YouTube darslar","url":"https://www.youtube.com"}],"related":["Robototexnika muhandisi","Fotograf"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Dron operatori$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/doctor%20in%20white%20coat%20with%20stethoscope%20in%20a%20modern%20hospital%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Insonlarga to'g'ridan-to'g'ri yordam","Hurmatli va barqaror kasb","Doimiy talab"],"cons":["Uzoq yillik o'qish","Yuqori mas'uliyat va stress","Tungi navbatlar"],"day_in_life":["Bemorlarni qabul qiladi","Tashxis qo'yib davo belgilaydi","Holatni kuzatib maslahat beradi"],"quiz":["Men odamlarga yordam berishni yoqtiraman","Men biologiya va kimyoni sevaman","Men mas'uliyatli va sabrliman","Men uzoq o'qishga tayyorman"],"resources":[{"label":"Khan Academy","url":"https://www.khanacademy.org"},{"label":"WHO","url":"https://www.who.int"}],"related":["Hamshira","O'qituvchi"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Shifokor$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/nurse%20caring%20for%20a%20patient%20in%20a%20bright%20hospital%20room%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Doimiy talab","Insonlarga g'amxo'rlik","Tezroq kasb egasi bo'lish"],"cons":["Jismonan charchatadi","Tungi navbatlar","Hissiy bosim"],"day_in_life":["Bemor holatini kuzatadi","Dori va muolaja beradi","Shifokorga yordam beradi"],"quiz":["Men g'amxo'r va sabrliman","Men odamlar bilan ishlashni yoqtiraman","Men chidamliman","Men biologiyani sevaman"],"resources":[{"label":"Khan Academy","url":"https://www.khanacademy.org"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Shifokor"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Hamshira$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/teacher%20explaining%20lesson%20to%20students%20in%20a%20bright%20classroom%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Yosh avlodga ta'sir","Hurmatli kasb","Barqaror ish va ta'til"],"cons":["Sabr ko'p talab qiladi","Ish hujjatlari ko'p","Maosh hamma joyda yuqori emas"],"day_in_life":["Darsga tayyorlanadi","Dars beradi va tushuntiradi","Vazifalarni tekshiradi"],"quiz":["Men bilimni boshqalarga ulashni yoqtiraman","Men sabrliman","Men ravon gapira olaman","Men bolalar bilan ishlashni sevaman"],"resources":[{"label":"Khan Academy","url":"https://www.khanacademy.org"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Shifokor","Jurnalist"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$O'qituvchi$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/civil%20engineer%20with%20hard%20hat%20reviewing%20blueprints%20at%20a%20construction%20site%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Aniq natija — bino va ko'priklar","Barqaror talab","Yaxshi daromad"],"cons":["Quyosh va sovuqda ish","Yuqori mas'uliyat","Xatolik qimmatga tushadi"],"day_in_life":["Loyiha chizmasini tekshiradi","Qurilishni nazorat qiladi","Mustahkamlikni hisoblaydi"],"quiz":["Men matematika va chizmachilikni yoqtiraman","Mening fazoviy tasavvurim yaxshi","Men mas'uliyatliman","Men real natija ko'rishni istayman"],"resources":[{"label":"Khan Academy","url":"https://www.khanacademy.org"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Duradgor (mebelchi)","Robototexnika muhandisi"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Quruvchi-muhandis$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/electrician%20working%20on%20electrical%20wiring%20panel%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Doimiy talab","Tez kasb egasi bo'lish","Mustaqil ishlash mumkin"],"cons":["Xavfsizlik qoidalari qat'iy","Jismoniy mehnat","Ehtiyotkorlik shart"],"day_in_life":["Simlarni ulaydi","Nosozlikni topadi","Xavfsizlikni tekshiradi"],"quiz":["Men qo'lim bilan ishlashni yoqtiraman","Men ehtiyotkor va aniqman","Men fizikani tushunaman","Men muammoni topib tuzata olaman"],"resources":[{"label":"YouTube darslar","url":"https://www.youtube.com"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Quruvchi-muhandis","Duradgor (mebelchi)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Elektrik$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/professional%20chef%20cooking%20in%20a%20restaurant%20kitchen%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Ijod va ta'm bilan ishlash","Hamma joyda kerak","O'z biznesini ochish mumkin"],"cons":["Oyoqda uzoq turish","Issiq va tez sur'at","Bayramlarda ish ko'p"],"day_in_life":["Mahsulotlarni tayyorlaydi","Taom pishiradi va bezaydi","Oshxona tartibini nazorat qiladi"],"quiz":["Men ovqat tayyorlashni yoqtiraman","Men ijodkorman","Men tez va ozodaman","Men bosim ostida ishlay olaman"],"resources":[{"label":"YouTube retseptlar","url":"https://www.youtube.com"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Novvoy"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Oshpaz$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/truck%20driver%20with%20delivery%20truck%20on%20highway%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Doimiy talab","Sayohat va mustaqillik","Maxsus oliy ta'lim shart emas"],"cons":["Uzoq vaqt yo'lda","Diqqat doim kerak","Uzoq o'tirish sog'liqqa ta'sir qiladi"],"day_in_life":["Yukni tekshirib ortadi","Marshrut bo'yicha yetkazadi","Hujjatlarni rasmiylashtiradi"],"quiz":["Men yo'lda bo'lishni yoqtiraman","Men diqqatli va mas'uliyatliman","Men mustaqil ishlashni sevaman","Men qoidalarga rioya qilaman"],"resources":[{"label":"YouTube","url":"https://www.youtube.com"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Elektrik"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Haydovchi (logistika)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/farmer%20working%20in%20green%20agricultural%20field%20with%20modern%20equipment%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["O'z mahsulotingni yetishtirasan","Tabiat bilan ish","Texnologiya bilan rivojlanmoqda"],"cons":["Ob-havoga bog'liq","Mavsumiy va og'ir mehnat","Daromad o'zgaruvchan"],"day_in_life":["Ekinni parvarish qiladi","Sug'orish va o'g'itlashni nazorat qiladi","Hosilni yig'adi"],"quiz":["Men tabiat va o'simliklarni yoqtiraman","Men mehnatkashman","Men rejalashtirishni bilaman","Men ochiq havoda ishlashni sevaman"],"resources":[{"label":"FAO","url":"https://www.fao.org"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Chorvador"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Fermer (dehqon)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/livestock%20farmer%20with%20cattle%20on%20a%20farm%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Doimiy oziq-ovqat manbai","Mustaqil ish","Qishloqda barqaror daromad"],"cons":["Kunlik g'amxo'rlik kerak","Jismoniy mehnat","Kasalliklar xavfi"],"day_in_life":["Hayvonlarni boqadi","Sog'lig'ini kuzatadi","Mahsulotini yig'adi"],"quiz":["Men hayvonlarni yaxshi ko'raman","Men g'amxo'r va chidamliman","Men erta turishga tayyorman","Men mas'uliyatliman"],"resources":[{"label":"YouTube","url":"https://www.youtube.com"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Fermer (dehqon)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Chorvador$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/tailor%20sewing%20clothes%20with%20fabric%20in%20a%20workshop%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Ijodiy va nozik ish","Uydan ishlash mumkin","O'z brendingni yaratish imkoni"],"cons":["Diqqat va sabr ko'p kerak","Buyurtmaga bog'liq","Uzoq o'tirib ishlash"],"day_in_life":["O'lcham oladi va bichadi","Kiyimni tikadi","Sinab, tuzatadi"],"quiz":["Men qo'l mehnatini yoqtiraman","Men did va aniqlikka egaman","Men sabrliman","Men chiroyli narsa yaratishni istayman"],"resources":[{"label":"YouTube darslar","url":"https://www.youtube.com"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Zardo'z (zardo'zlik)","Atlas to'quvchi (ipakchilik)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Tikuvchi$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/carpenter%20building%20wooden%20furniture%20in%20a%20woodworking%20workshop%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Qo'ling bilan real buyum yaratasan","Doimiy talab","O'z ustaxonangni ochish mumkin"],"cons":["Jismoniy mehnat","Chang va shovqin","Aniqlik va vaqt talab qiladi"],"day_in_life":["O'lchab, yog'ochni kesadi","Qismlarni yig'adi","Sayqal berib pardozlaydi"],"quiz":["Men qo'l bilan yasashni yoqtiraman","Mening fazoviy tasavvurim yaxshi","Men aniq va sabrliman","Men chizmachilikni tushunaman"],"resources":[{"label":"YouTube","url":"https://www.youtube.com"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Quruvchi-muhandis","Kulol (kulolchilik)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Duradgor (mebelchi)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/baker%20making%20fresh%20bread%20in%20a%20bakery%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Doimiy talab","Tez kasb egasi bo'lish","O'z nonvoyxonangni ochish mumkin"],"cons":["Erta turish","Issiq oldida ish","Oyoqda turish"],"day_in_life":["Xamir qoradi","Non va shirinlik yopadi","Sotuvga tayyorlaydi"],"quiz":["Men ovqat tayyorlashni yoqtiraman","Men erta turishga tayyorman","Men aniq va ozodaman","Men mehnatkashman"],"resources":[{"label":"YouTube retseptlar","url":"https://www.youtube.com"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Oshpaz"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Novvoy$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/potter%20shaping%20clay%20pottery%20on%20a%20wheel%20in%20a%20traditional%20workshop%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Milliy meros va san'at","Noyob qo'l ishi qadrlanadi","Ijodiy erkinlik"],"cons":["Sabr va yillik tajriba kerak","Daromad beqaror","Jismoniy mehnat"],"day_in_life":["Loyni tayyorlaydi","Charxda idish shakllantiradi","Naqsh berib o'choqda pishiradi"],"quiz":["Men qo'l mehnati va san'atni yoqtiraman","Men sabrliman","Men ijodkorman","Men an'analarni qadrlayman"],"resources":[{"label":"Hunarmand uyushmasi","url":"https://hunarmand.uz"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Naqqosh (naqqoshlik)","Ganchkor (ganch o'ymakorligi)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Kulol (kulolchilik)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/gold%20thread%20embroidery%20artisan%20working%20on%20traditional%20uzbek%20chapan%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Noyob milliy san'at","Yuqori qadrlanadi","Ijodiy va nafis ish"],"cons":["Juda sabr talab qiladi","Ko'zga zo'r beradi","Sekin daromad"],"day_in_life":["Naqsh chizmasini tayyorlaydi","Zar ip bilan kashta tikadi","Buyumni pardozlaydi"],"quiz":["Men nozik qo'l ishini yoqtiraman","Men juda sabrliman","Men did va go'zallikni sevaman","Men an'analarni qadrlayman"],"resources":[{"label":"Hunarmand uyushmasi","url":"https://hunarmand.uz"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Tikuvchi","Naqqosh (naqqoshlik)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Zardo'z (zardo'zlik)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/coppersmith%20engraving%20patterns%20on%20a%20copper%20plate%20traditional%20workshop%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Qadimiy milliy hunar","Noyob buyumlar qadrlanadi","Ijodiy ish"],"cons":["Jismoniy kuch kerak","Shovqinli ish","Sabr va tajriba talab qiladi"],"day_in_life":["Mis varaqni shakllantiradi","Bolg'a bilan naqsh soladi","Buyumni jilolaydi"],"quiz":["Men qo'l mehnatini yoqtiraman","Men kuchli va sabrliman","Men did va san'atni sevaman","Men an'analarni qadrlayman"],"resources":[{"label":"Hunarmand uyushmasi","url":"https://hunarmand.uz"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Kulol (kulolchilik)","Naqqosh (naqqoshlik)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Misgar (misgarlik)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/master%20carving%20intricate%20ganch%20plaster%20patterns%20on%20wall%20traditional%20uzbek%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Milliy me'morchilik durdonasi","Noyob mahorat","Ijodiy ish"],"cons":["Nozik va sekin ish","Sabr ko'p kerak","Chang bilan ish"],"day_in_life":["Naqsh eskizini chizadi","Ganchni o'yib naqsh yasaydi","Devorga o'rnatadi"],"quiz":["Men nozik qo'l ishini yoqtiraman","Men sabrli va aniqman","Men geometriya va san'atni sevaman","Men an'analarni qadrlayman"],"resources":[{"label":"Hunarmand uyushmasi","url":"https://hunarmand.uz"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Naqqosh (naqqoshlik)","Kulol (kulolchilik)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Ganchkor (ganch o'ymakorligi)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/artisan%20painting%20traditional%20uzbek%20floral%20ornament%20on%20wood%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Milliy san'at va ijod","Noyob mahorat qadrlanadi","Go'zallik yaratasan"],"cons":["Sabr va tajriba kerak","Daromad beqaror","Diqqat ko'p talab qiladi"],"day_in_life":["Naqsh kompozitsiyasini tuzadi","Gul va islimiy naqsh chizadi","Buyumni pardozlaydi"],"quiz":["Men chizish va rangni yoqtiraman","Men sabrli va aniqman","Men ijodkorman","Men an'analarni qadrlayman"],"resources":[{"label":"Hunarmand uyushmasi","url":"https://hunarmand.uz"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Ganchkor (ganch o'ymakorligi)","Grafik dizayner"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Naqqosh (naqqoshlik)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/weaver%20making%20colorful%20uzbek%20atlas%20silk%20fabric%20on%20a%20loom%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Mashhur milliy mato","Ijodiy va rangli ish","Eksportga chiqadi"],"cons":["Sekin va mashaqqatli","Sabr ko'p kerak","Daromad beqaror"],"day_in_life":["Pilladan ip ochadi","Ipni bo'yaydi","Dastgohda atlas to'qiydi"],"quiz":["Men rang va go'zallikni sevaman","Men sabrliman","Men qo'l mehnatini yoqtiraman","Men an'analarni qadrlayman"],"resources":[{"label":"Hunarmand uyushmasi","url":"https://hunarmand.uz"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Tikuvchi","Zardo'z (zardo'zlik)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Atlas to'quvchi (ipakchilik)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/vintage%20telephone%20switchboard%20operator%20connecting%20cables%20retro%20black%20and%20white%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["O'z davrida muhim ish edi","Aloqa rivojiga hissa","Tez va aniqlik mahorati"],"cons":["Avtomatlashtirish tufayli yo'qoldi","Bir xil takror ish","Hozir deyarli kerak emas"],"day_in_life":["Qo'ng'iroqni qabul qiladi","Simlarni ulab bog'laydi","Aloqani uzadi"],"quiz":["Men odamlar bilan gaplashishni yoqtiraman","Men tez va aniqman","Men diqqatliman","Men yangi texnologiyaga moslashaman"],"resources":[{"label":"Wikipedia","url":"https://uz.wikipedia.org"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Mashinkachi (yozuv mashinkasi)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Telefon kommutatori operatori$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/vintage%20typist%20typing%20on%20old%20typewriter%20retro%20office%20black%20and%20white%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Tez yozish mahorati","O'z davrida talab katta edi","Aniqlik va diqqat"],"cons":["Kompyuter o'rnini egalladi","Bir xil ish","Hozir alohida kasb emas"],"day_in_life":["Qo'lyozmani o'qiydi","Mashinkada teradi","Xatosini tuzatadi"],"quiz":["Men tez yozaman","Men diqqatli va aniqman","Men matn bilan ishlashni yoqtiraman","Men kompyuterni o'rganishga tayyorman"],"resources":[{"label":"Wikipedia","url":"https://uz.wikipedia.org"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Telefon kommutatori operatori"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Mashinkachi (yozuv mashinkasi)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/vintage%20cinema%20projectionist%20operating%20film%20projector%20retro%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Kino sehrini olib kelardi","Texnik mahorat","Madaniyatga hissa"],"cons":["Raqamli kino o'rnini egalladi","Tungi ish","Hozir kam kerak"],"day_in_life":["Plyonkani proyektorga o'rnatadi","Filmni namoyish qiladi","Apparaturani tekshiradi"],"quiz":["Men texnikani yoqtiraman","Men diqqatli va aniqman","Men kino san'atini sevaman","Men yangilikka moslashaman"],"resources":[{"label":"Wikipedia","url":"https://uz.wikipedia.org"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Fotograf","Animator (3D rassom)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Kinomexanik$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/vintage%20lamplighter%20lighting%20a%20street%20gas%20lamp%20at%20dusk%20retro%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Shaharga yorug'lik berardi","O'z davrida zarur edi","Mehnatsevarlik ramzi"],"cons":["Elektr tufayli butunlay yo'qoldi","Har kun piyoda yurish","Hozir mavjud emas"],"day_in_life":["Kechqurun fonarlarni yoqadi","Tunda nazorat qiladi","Tongda o'chiradi"],"quiz":["Men tartibni yoqtiraman","Men mas'uliyatliman","Men ochiq havoda yurishni sevaman","Men yangi kasblarni o'rganishga tayyorman"],"resources":[{"label":"Wikipedia","url":"https://uz.wikipedia.org"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Elektrik"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Fonarchi (ko'cha chiroqchisi)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/watchmaker%20repairing%20mechanical%20watch%20with%20tiny%20tools%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Nozik va aniq mahorat","Qadimiy buyumlar uchun qadrli","Mustaqil ish"],"cons":["Arzon elektronika tufayli kamaydi","Juda sabr talab qiladi","Mijoz kam"],"day_in_life":["Mexanizmni ochadi","Mayda detalni tuzatadi","Yig'ib sinaydi"],"quiz":["Men mayda detallar bilan ishlashni yoqtiraman","Men juda sabrliman","Men diqqatli va aniqman","Men texnikani tushunaman"],"resources":[{"label":"Wikipedia","url":"https://uz.wikipedia.org"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Elektrik"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Soatsoz va radiousta$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/journalist%20interviewing%20person%20with%20microphone%20and%20notebook%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Voqealarning markazida bo'lasan","Jamiyatga ta'sir","Qiziqarli odamlar bilan tanishuv"],"cons":["Muddatlar qisqa","Ba'zan xavfli vaziyatlar","Beqaror ish vaqti"],"day_in_life":["Mavzu va manba izlaydi","Intervyu olib yozadi","Maqolani tahrirlab e'lon qiladi"],"quiz":["Men yozishni va savol berishni yoqtiraman","Men qiziquvchanman","Men haqiqatni izlayman","Men jasoratliman"],"resources":[{"label":"YouTube","url":"https://www.youtube.com"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Kontent-kreator (SMM mutaxassisi)","O'qituvchi"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Jurnalist$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/content%20creator%20filming%20video%20with%20smartphone%20and%20ring%20light%20studio%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Ijodiy erkinlik","Tez o'sayotgan soha","Uydan ishlash mumkin"],"cons":["Doimiy g'oya kerak","Trend juda tez o'zgaradi","Daromad boshida beqaror"],"day_in_life":["G'oya va ssenariy o'ylaydi","Video va post tayyorlaydi","Auditoriya bilan ishlaydi"],"quiz":["Men ijodkor va g'oyalarga boyman","Men ijtimoiy tarmoqni yaxshi bilaman","Men kamera oldida erkinman","Men trendlarni sezaman"],"resources":[{"label":"Canva","url":"https://www.canva.com"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Grafik dizayner","Jurnalist"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Kontent-kreator (SMM mutaxassisi)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/graphic%20designer%20creating%20logo%20on%20computer%20creative%20studio%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Ijodiy va talabchan soha","Frilans imkoniyati","Har biznesga kerak"],"cons":["Did har xil — qayta ishlash ko'p","Trend kuzatish shart","Muddat bosimi"],"day_in_life":["Mijoz g'oyasini o'rganadi","Logotip va maket yaratadi","Tahrirlab topshiradi"],"quiz":["Men chizish va rangni yoqtiraman","Men ijodkorman","Men did va go'zallikni sevaman","Men kompyuter dasturlarini o'rganaman"],"resources":[{"label":"Figma","url":"https://www.figma.com"},{"label":"Behance","url":"https://www.behance.net"}],"related":["UX/UI dizayner","Animator (3D rassom)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Grafik dizayner$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/3d%20animator%20creating%20character%20animation%20on%20computer%20studio%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Ijod va texnologiya uyg'unligi","O'sayotgan soha","Multfilm va o'yinlar yaratasan"],"cons":["Ko'p vaqt va sabr","Kuchli kompyuter kerak","Murakkab dasturlar"],"day_in_life":["Personaj va sahnani chizadi","Harakatga keltiradi","Renderlab tekshiradi"],"quiz":["Men chizish va multfilmni yoqtiraman","Men sabrliman","Men kompyuterda ijod qilaman","Mening fazoviy tasavvurim yaxshi"],"resources":[{"label":"Blender","url":"https://www.blender.org"},{"label":"YouTube","url":"https://www.youtube.com"}],"related":["Grafik dizayner","Kinomexanik"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Animator (3D rassom)$q$;

UPDATE public.bilimnoma_entries SET image_url='https://image.pollinations.ai/prompt/photographer%20taking%20photos%20with%20professional%20camera%20outdoors%20realistic%20photo?width=1200&height=600&nologo=true',
 details = details || $j${"pros":["Ijodiy va erkin ish","Frilans imkoniyati","Go'zal lahzalarni saqlaysan"],"cons":["Texnika qimmat","Daromad beqaror","Tahrirlash ko'p vaqt oladi"],"day_in_life":["Suratga olishni rejalashtiradi","Surat oladi","Tahrirlab topshiradi"],"quiz":["Men go'zallikni ko'ra olaman","Men ijodkorman","Men texnikani yoqtiraman","Men sabr bilan ishlayman"],"resources":[{"label":"YouTube darslar","url":"https://www.youtube.com"},{"label":"Wikipedia","url":"https://uz.wikipedia.org"}],"related":["Dron operatori","Animator (3D rassom)"]}$j$::jsonb
 WHERE section='kasblar' AND title=$q$Fotograf$q$;
